-- Migration: 001_initial_schema.sql
-- Create initial tables for AI Support Automation

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles Table
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    avatar_url TEXT,
    role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'manager', 'agent', 'viewer')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- Automatically create profile on new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, email, avatar_url, role)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
        NEW.email,
        NEW.raw_user_meta_data->>'avatar_url',
        'viewer' -- default role, can be upgraded by admin later
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Tickets Table
CREATE TABLE public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'In Progress', 'Resolved', 'Closed')),
    category TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
    sentiment TEXT NOT NULL CHECK (sentiment IN ('Positive', 'Neutral', 'Urgent', 'Angry', 'Frustrated')),
    summary TEXT NOT NULL,
    customer_intent TEXT NOT NULL,
    suggested_action TEXT NOT NULL,
    suggested_response TEXT NOT NULL,
    confidence_score NUMERIC NOT NULL DEFAULT 0.0,
    key_entities JSONB NOT NULL DEFAULT '[]'::jsonb,
    agent_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

CREATE TRIGGER update_tickets_updated_at
BEFORE UPDATE ON public.tickets
FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();


-- 3. Automation Actions Table
CREATE TABLE public.automation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'completed', 'dismissed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    assigned_to UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);
-- Migration: 002_indexes.sql
-- Create performance indexes for querying tickets and automation actions

-- Tickets Indexes
CREATE INDEX IF NOT EXISTS idx_tickets_ticket_number ON public.tickets (ticket_number);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.tickets (status);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON public.tickets (priority);
CREATE INDEX IF NOT EXISTS idx_tickets_category ON public.tickets (category);
CREATE INDEX IF NOT EXISTS idx_tickets_sentiment ON public.tickets (sentiment);
CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON public.tickets (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tickets_customer_email ON public.tickets (customer_email);

-- Automation Actions Indexes
CREATE INDEX IF NOT EXISTS idx_automation_actions_ticket_id ON public.automation_actions (ticket_id);
CREATE INDEX IF NOT EXISTS idx_automation_actions_status ON public.automation_actions (status);
CREATE INDEX IF NOT EXISTS idx_automation_actions_assigned_to ON public.automation_actions (assigned_to);
-- Migration: 003_rls_policies.sql
-- Enable Row Level Security (RLS) on all application tables and define policies

-- 1. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_actions ENABLE ROW LEVEL SECURITY;

-- 2. Profiles Policies
-- Users can view their own profile
CREATE POLICY "Users can view own profile"
ON public.profiles FOR SELECT
USING (auth.uid() = id);

-- Admins and managers can view all profiles
CREATE POLICY "Admins and managers can view all profiles"
ON public.profiles FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role IN ('admin', 'manager')
    )
);

-- Users can update their own profile (e.g. name, avatar, but not role)
CREATE POLICY "Users can update own profile"
ON public.profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (
    -- Prevent users from escalating their own role
    role = (SELECT role FROM public.profiles WHERE id = auth.uid())
);

-- Admins can update any profile (including roles)
CREATE POLICY "Admins can update all profiles"
ON public.profiles FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role = 'admin'
    )
);


-- 3. Tickets Policies
-- Everyone (all authenticated users) can view tickets for now.
-- You might restrict viewers from seeing PII in a more complex setup.
CREATE POLICY "All authenticated users can view tickets"
ON public.tickets FOR SELECT
USING (auth.uid() IS NOT NULL);

-- Agents, managers, and admins can insert tickets
CREATE POLICY "Support staff can insert tickets"
ON public.tickets FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role IN ('agent', 'manager', 'admin')
    )
);

-- Agents, managers, and admins can update tickets
CREATE POLICY "Support staff can update tickets"
ON public.tickets FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role IN ('agent', 'manager', 'admin')
    )
);


-- 4. Automation Actions Policies
-- All authenticated users can view actions
CREATE POLICY "All authenticated users can view automation actions"
ON public.automation_actions FOR SELECT
USING (auth.uid() IS NOT NULL);

-- Support staff can insert actions (though usually this is done by the backend AI agent)
CREATE POLICY "Support staff can insert actions"
ON public.automation_actions FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role IN ('agent', 'manager', 'admin')
    )
);

-- Support staff can update actions (e.g., approve, dismiss, complete)
CREATE POLICY "Support staff can update actions"
ON public.automation_actions FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM public.profiles p
        WHERE p.id = auth.uid() AND p.role IN ('agent', 'manager', 'admin')
    )
);
-- Seed Demo Data
-- Note: User profiles must be inserted through auth.users creation normally,
-- but for demo seeding we insert dummy profiles bypassing auth for relationships,
-- or we can just leave `assigned_to` null if auth isn't setup locally yet.

INSERT INTO public.tickets (
    ticket_number, customer_name, customer_email, subject, message, status,
    category, priority, sentiment, summary, customer_intent, suggested_action,
    suggested_response, confidence_score, key_entities, created_at
) VALUES
(
    'TKT-1001', 'Alice Johnson', 'alice.j@example.com', 'Cannot log in to my account',
    'Hi, I have been trying to log in all morning but it keeps saying invalid password even though I am sure it is correct.',
    'Open', 'Account Access', 'High', 'Frustrated',
    'Customer is unable to log into their account due to invalid password errors.',
    'Password Reset or Account Unlocking', 'Send password reset link and check account status.',
    'Hello Alice, I am sorry to hear you are having trouble logging in. I have sent a password reset link to your email.',
    0.92, '[{"entity": "account", "type": "product_feature"}, {"entity": "password", "type": "credential"}]',
    NOW() - INTERVAL '2 hours'
),
(
    'TKT-1002', 'Bob Smith', 'bob.smith@example.com', 'Billing discrepancy on last invoice',
    'I noticed I was charged $50 instead of my usual $30. Can you explain this?',
    'In Progress', 'Billing & Payments', 'Medium', 'Neutral',
    'Customer is questioning an overcharge on their recent invoice.',
    'Invoice Explanation or Refund', 'Review invoice #INV-XXXX and provide breakdown of charges.',
    'Hello Bob, thank you for reaching out. The additional $20 was due to the pro-rated upgrade you made mid-month.',
    0.88, '[{"entity": "$50", "type": "amount"}, {"entity": "$30", "type": "amount"}]',
    NOW() - INTERVAL '1 day'
),
(
    'TKT-1003', 'Carol Davis', 'carol.d@example.com', 'System is down completely',
    'The entire dashboard is throwing 500 errors. We cannot process any orders right now. Fix this ASAP!',
    'Open', 'Technical Issue', 'Critical', 'Angry',
    'Customer is reporting a complete system outage preventing order processing.',
    'Immediate Technical Escalation', 'Escalate to engineering on-call immediately.',
    'Hello Carol, we are aware of the dashboard outage and our engineering team is investigating it as a top priority.',
    0.98, '[{"entity": "dashboard", "type": "product_feature"}, {"entity": "500 errors", "type": "error_code"}]',
    NOW() - INTERVAL '15 minutes'
);

INSERT INTO public.automation_actions (
    ticket_id, action_type, title, description, priority, status
) VALUES
(
    (SELECT id FROM public.tickets WHERE ticket_number = 'TKT-1003'),
    'escalate', 'Critical System Outage Escalation',
    'Automatically escalate ticket to engineering on-call due to Critical priority and Technical Issue category.',
    'Critical', 'pending'
),
(
    (SELECT id FROM public.tickets WHERE ticket_number = 'TKT-1001'),
    'human_review', 'Review Account Lockout',
    'High priority account issue requires human review before triggering automated password reset.',
    'High', 'pending'
);
